services:
  RateLimiter\RateLimiter\RateLimiterConfig:
    arguments:
      $maxAttempts: '%rate_limiter.max_attempts%'
      $retryIntervalInSeconds: '%rate_limiter.interval%'
      $blockDurationInSeconds: '%rate_limiter.block_duration%'
  RateLimiter\RateLimiter\RateLimiter:
    arguments:
      $redis: '@redis'
      $config: '@RateLimiter\RateLimiter\RateLimiterConfig'
